consul:
  consul_url: "127.0.0.1"
  consul_port: 8500

notify:
  dingding_url: "https://oapi.dingtalk.com/robot/send?access_token=xxx"
  secret: xxx

running:
  scheduleIntervel: 10 #per minutes
  maxNotify: 2